############################
#
# Build:
#    docker-compose build
#
# Run:
#    docker-compose up
# and later
#    docker-compose down
# elsewhere.

version: "2"

services:
  tor:
    #build:
    #  context: .
    #  dockerfile: Tor
    image: akrey/onion
    volumes:
      - data:/data

  ssh:
    #build:
    #  context: .
    #  dockerfile: Ssh
    image: akrey/shell
    volumes:
      - data:/data

volumes:
  data:
